<?php

/**
 * @file
 * Install, update and uninstall functions to help with development.
 */

/**
 * Stored variable prefix.
 */
define('US_DEV_VARIABLE_PREFIX', 'us_dev_var_orig__');

/**
 * Stage file proxy origin URL.
 */
define('US_DEV_STAGE_FILE_PROXY_ORIGIN', 'http://utopiaschool.org');

/**
 * Implements hook_enable().
 */
function us_dev_enable() {
  us_dev_enable_dev_modules();
  us_dev_hijack_variables();
  us_dev_hijack_permissions();
}

/**
 * Implements hook_disable().
 */
function us_dev_disable() {
  us_dev_disable_dev_modules();
  us_dev_reset_variables();
  us_dev_reset_permissions();
}

/**
 * Defines development-only modules.
 */
function us_dev_define_modules() {
  return array(
    'dblog',
    'devel',
    'field_ui',
    'views_ui',
    'stage_file_proxy',
    'maillog',
  );
}

/**
 * Enables development modules.
 */
function us_dev_enable_dev_modules() {
  $modules = us_dev_define_modules();
  module_enable($modules);

  return features_log(t('The following modules were enabled: @modules', array('@modules' => implode(', ', $modules))), 'status');
}

/**
 * Disables development modules.
 */
function us_dev_disable_dev_modules() {
  $modules = us_dev_define_modules();
  module_disable($modules);
  drupal_uninstall_modules($modules);

  return features_log(t('The following modules were enabled: @modules', array('@modules' => implode(', ', $modules))), 'status');
}

/**
 * Defines development variables.
 *
 * @return array
 *   An associative array of dev-only variable values, keyed by variable name.
 */
function us_dev_define_variables() {
  return array(
    'stage_file_proxy_origin' => US_DEV_STAGE_FILE_PROXY_ORIGIN,
    'maillog_send' => 0,
  );
}

/**
 * Hijacks development variables.
 */
function us_dev_hijack_variables() {
  foreach (us_dev_define_variables() as $name => $value) {
    us_dev_store_variable($name);
    variable_set($name, $value);
  }
}

/**
 * Resets development variables to their original state.
 */
function us_dev_reset_variables() {
  foreach (array_keys(us_dev_define_variables()) as $name) {
    if ($value = us_dev_retrieve_stored_variable($name)) {
      variable_set($name, $value);
    }
    else {
      variable_del($name);
    }
  }
}

/**
 * Stores development variable values before we set them.
 */
function us_dev_store_variable($name) {
  if ($value = variable_get($name)) {
    variable_set(US_DEV_VARIABLE_PREFIX . $name , $value);
  }
}

/**
 * Retrieves stored development variable values from before we set them.
 *
 * @return mixed | null
 *   The stored variable value from before we set a dev value, or NULL.
 */
function us_dev_retrieve_stored_variable($name) {
  return variable_get(US_DEV_VARIABLE_PREFIX . $name);
}

/**
 * Hijacks development user permissions.
 */
function us_dev_hijack_permissions() {
  us_dev_store_permissions();
  foreach (us_dev_define_permissions() as $rid => $role_permissions) {
    user_role_change_permissions($rid, $role_permissions);
  }
}

/**
 * Resets development user permissions to their original state.
 *
 * @todo Check to make sure this doesn't let revoked permissions defined in
 *   us_dev_define_permissions() to linger, since user_role_permissions() only
 *   returns permisions that are TRUE (does not contain all FALSE ones).
 */
function us_dev_reset_permissions() {
  foreach (variable_get(US_DEV_VARIABLE_PREFIX . 'permissions') as $rid => $role_permissions) {
    user_role_change_permissions($rid, $role_permissions);
  }
}

/**
 * Defines development user permissions.
 *
 * @return array
 *   Matches the $permissions param for user_role_change_permissions().
 *
 * @see user_role_change_permissions()
 */
function us_dev_define_permissions() {
  return array(
    DRUPAL_ANONYMOUS_RID => array(
      'access devel information' => TRUE,
    ),
    DRUPAL_AUTHENTICATED_RID => array(
      'access devel information' => TRUE,
    ),
  );
}

/**
 * Stores development user permissions before we set them.
 */
function us_dev_store_permissions() {
  // Get and store all permissions.
  $permissions = user_role_permissions(array_keys(user_roles()));
  variable_set(US_DEV_VARIABLE_PREFIX . 'permissions', $permissions);
}
