<?php
/**
 * @file
 * Code for the us_people feature.
 */

include_once 'us_people.features.inc';

/**
 * User name field.
 */
define ('US_PEOPLE_NAME_FIELD', 'field_name');

/**
 * Implements hook_username_alter().
 *
 * The Name module has way too much that we don't want. But it also solves some
 * things in a nicer way than Realname module (which has other things we don't
 * want, and also does not support profile2).
 *
 * @see name_username_alter()
 */
function us_people_username_alter(&$name, $account) {
  // Don't alter anonymous users or objects that do not have any user ID.
  if (empty($account->uid)) {
    return;
  }

  // We store the user name in a custom profile2 field.
  if (field_info_instance('profile2', US_PEOPLE_NAME_FIELD, 'main') && $data = profile2_load_by_user($account, 'main')) {
    if ($items = field_get_items('profile2', $data, US_PEOPLE_NAME_FIELD)) {
      if (isset($items[0]['safe_value']) && drupal_strlen($items[0]['safe_value'])) {
        $name = $items[0]['safe_value'];
      }
    }
  }
}

/**
 * Preprocess the themed user picture to have a default.
 *
 * @see template_preprocess_user_picture()
 */
function us_people_preprocess_user_picture(&$variables) {
  $variables['user_picture'] = '';
  if (variable_get('user_pictures', 0)) {
    $account = $variables['account'];
    if (!empty($account->picture)) {
      if (is_numeric($account->picture)) {
        $account->picture = file_load($account->picture);
      }
      if (!empty($account->picture->uri)) {
        $filepath = $account->picture->uri;
      }
    }
    elseif (variable_get('user_picture_default', '')) {
      $filepath = variable_get('user_picture_default', '');
    }
    if (isset($filepath)) {
      $alt = t("@user's picture", array('@user' => format_username($account)));
      // Allow passing a user_picture_style key through the variables param.
      $style = isset($variables['user_picture_style']) ? $variables['user_picture_style'] : variable_get('user_picture_style', '');
      // If the image does not have a valid Drupal scheme (for eg. HTTP),
      // don't load image styles.
      if (module_exists('image') && file_valid_uri($filepath) && !empty($style)) {
        $variables['user_picture'] = theme('image_style', array('style_name' => $style, 'path' => $filepath, 'alt' => $alt, 'title' => $alt));
      }
      else {
        $variables['user_picture'] = theme('image', array('path' => $filepath, 'alt' => $alt, 'title' => $alt));
      }
      if (!empty($account->uid) && user_access('access user profiles')) {
        $attributes = array('attributes' => array('title' => t('View user profile.')), 'html' => TRUE);
        $variables['user_picture'] = l($variables['user_picture'], "user/$account->uid", $attributes);
      }
    }
  }
}
