<?php
/**
 * @file
 * Code for the us_contact feature.
 */

include_once 'us_contact.features.inc';

/**
 * Implements hook_field_access().
 *
 * Note field_permissions module is overkill here.
 */
function us_contact_field_access($op, $field, $entity_type, $entity, $account) {
  $fields = array(
    'field_internal_notes',
    'field_internal_contact',
    'field_internal_status',
    'field_related_classes',
  );
  if ($op == 'edit' && $entity_type == 'entityform' && in_array($field['field_name'], $fields)) {
    return in_array('committee', $account->roles);
  }

  return TRUE;
}
